### ISSUE TITLE
Feedback on media types and general integration

### ISSUE THREAD

**Issue by stevokk** [silvia-odwyer/lightbox.js#21]
Hi! 

I have just purchased and starting integrating your library as your demo on mobile seemed worth the money but it's a little slow to do because I don't think you've yet documented the video or youtube support, and also no mention of passing an images prop directly as far as I can see in the docs.

At this point I'm a little lost on best practice, do I copy from closed github issues, or follow the pages of example I see?

Some feedback below from my initial look at the code, hopefully this doesn't annoy you in any way, they're not demands!

1. Documentation for the video, picture and youtube support
2. Document passing the images prop instead of generating img elements (I want to support the new "original" param)
3. Allow passing src instead of videoSrc for video elements - if picture support requires srcSet, why differ with video props not following spec name? also if the type is "video" and not "htmlVideo" could it be assumed they want the html video element?
4. Support video.poster as posterSrc [Mozilla - video](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video)
5. Support src for YouTube as a complete URL override to support more flags without library support [Youtube Docs](https://developers.google.com/youtube/player_parameters#Parameters)
6. Allow PDF or other browser supported content as iframe src? Can enforce an preset image dataURL in prop.thumbnail & prop.src as the link/html to iframe.

But honestly, right now I only need htmlVideo and image & they'll work once I create this 'images' prop :)

**Comment by silvia-odwyer** [comment]
@stevokk Hi Steven, Thanks for mentioning those points regarding the documentation for video support. I will wrap up the current documentation written and publish this, I've created guides for the video support along with YouTube embeds too.

Those are some great feature requests also, I will get started on these, and will keep you updated once these are completed ✅ 

For your use case, I've created an example to showcase how to implement the functionality required. 

Firstly, create the array of media elements to be displayed:
```js
const mediaItems = [
  {
    type: "htmlVideo", 
    videoSrc:"http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    thumbnail:"https://peach.blender.org/wp-content/uploads/bbb-splash.png"
  }, 
  { 
    original: "https://source.unsplash.com/OZACaaUskhg/1700x950",
    src: "https://source.unsplash.com/OZACaaUskhg/900x450", 
    alt: "A blue sky overlooking a mountain range with a forest in the foreground"
  },
  { 
    type: "yt", 
    videoID :"IWVJq-4zW24",
    thumbnail: "https://img.youtube.com/vi/IWVJq-4zW24/hqdefault.jpg"
  }
]
```

Here's the JSX to include the lightbox:
```jsx
<SlideshowLightbox 
  images={mediaItems} 
  showLoader={true} 
  showThumbnails={true} 
  open={isOpen} 
  onClose={() =>{setIsOpen(false)}}>     
</SlideshowLightbox>
```

This example includes the `original` attribute for the image as you mentioned and displays a loader while the image is loading. Also, you mentioned that you'll be passing the images via the images prop, so if you'd like to open the lightbox through a button for example, this can be done via toggling the `open` prop.

Hopefully this helps, and if you have any queries, be sure to let me know. I'm always glad to help!

**Comment by stevokk** [comment]
Thank you @silvia-odwyer, great to see a quick and helpful response! I understand that when you're adding a lot of features, documentation can sometimes lag behind. I appreciate the example for my use case also! 😃

**Comment by stevokk** [comment]
@silvia-odwyer I've got everything running smoothly apart from 1 bug (I can replicate using your above example).

Using your example code on version 0.6.4 you can trigger an error when trying to go from slide 0 to the last like using either the arrow keys or button.

```
Cannot read properties of undefined (reading 'loaded')
TypeError: Cannot read properties of undefined (reading 'loaded')
    at initLoader (http://localhost:3000/static/js/bundle.js:77478:49)
    at prevSlide (http://localhost:3000/static/js/bundle.js:77563:5)
    at onKeyHandle (http://localhost:3000/static/js/bundle.js:78259:7)
    at KeyHandler._this.handleKey (http://localhost:3000/static/js/bundle.js:78837:7)
```

Interestingly, if you go forwards and make 1+ loop of the slideshow, going backwards will only fail when you've effectively "unwound" the looping count for lack of a better explanation. Unfortunately I cannot reproduce on your documentation demos, but maybe they use a previous version.

Full steps:
1. Use your mediaItems example
2. starting at slide 0, click either the left arrow or left button to see the console error
3. go forwards an entire loop so you end up back on slide 0, now go backwards a full loop until it errors.

I'm not 100% clear on what the loaded boolean does, but maybe it's being lost with state or prop changes?

Happy to move to a new issue if this isn't related, I just don't want people encountering the same bug based off this github issue.

**Comment by silvia-odwyer** [comment]
@stevokk Hi Steven, 
I've just implemented a fix for this, and released a new version of the library. If you install the latest version of the library, the bug should now be resolved. Thanks for letting me know about this bug, it's much appreciated! 

The documentation is also in progress, and should be published in the coming day or so ✅
